# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genqrcode.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgenqrcode.proto\x12\tgenqrcode\"\x19\n\x0brequestCode\x12\n\n\x02rq\x18\x01 \x01(\t\"\x1b\n\x0cresponseCode\x12\x0b\n\x03res\x18\x01 \x01(\t2O\n\x10GenQrCodeService\x12;\n\x08Generate\x12\x16.genqrcode.requestCode\x1a\x17.genqrcode.responseCodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genqrcode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTCODE']._serialized_start=30
  _globals['_REQUESTCODE']._serialized_end=55
  _globals['_RESPONSECODE']._serialized_start=57
  _globals['_RESPONSECODE']._serialized_end=84
  _globals['_GENQRCODESERVICE']._serialized_start=86
  _globals['_GENQRCODESERVICE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
