# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import genqrcode_pb2 as genqrcode__pb2


class GenQrCodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/genqrcode.GenQrCodeService/Generate',
                request_serializer=genqrcode__pb2.requestCode.SerializeToString,
                response_deserializer=genqrcode__pb2.responseCode.FromString,
                )


class GenQrCodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenQrCodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=genqrcode__pb2.requestCode.FromString,
                    response_serializer=genqrcode__pb2.responseCode.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genqrcode.GenQrCodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GenQrCodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genqrcode.GenQrCodeService/Generate',
            genqrcode__pb2.requestCode.SerializeToString,
            genqrcode__pb2.responseCode.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
